server:
  port: 8080

spring:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: ${ISSUER_URI}

  datasource:
    platform: postgres
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

config:
  uris:
    react-app-uri: ${REACT_APP_URI}

logging:
  level:
    org:
      springframework:
        security:
          - TRACE
          - oauth2: TRACE
